import os
import json
import asyncio
import google.generativeai as genai


# Default clinical report catalog
CLINICAL_CATALOG = {
    "PNEUMONIA": {
        "clinical_explanation": (
            "The computer-assisted deep learning model detected significant focal densities and patchy opacities "
            "within the pulmonary fields. These visual anomalies correspond to alveolar infiltration and fluid "
            "consolidation, suggesting an active infection of the lung parenchyma (pneumonia)."
        ),
        "possible_causes": [
            "Bacterial infection (e.g., Streptococcus pneumoniae, Haemophilus influenzae)",
            "Viral pneumonia (e.g., Influenza virus, Respiratory Syncytial Virus, SARS-CoV-2)",
            "Atypical pathogens (e.g., Mycoplasma pneumoniae, Chlamydophila pneumoniae)",
            "Aspiration pneumonia secondary to micro-aspiration of secretions"
        ],
        "recommendations": [
            "Schedule an urgent clinical evaluation with a primary care physician or pulmonologist.",
            "Obtain a Complete Blood Count (CBC) with differential, and sputum gram stain/cultures.",
            "Consider empiric broad-spectrum antibiotic therapy or targeted antivirals as clinically indicated.",
            "Monitor blood oxygen saturation (SpO2) using pulse oximetry, and seek immediate emergency care if levels drop below 92%."
        ],
        "lifestyle_suggestions": [
            "Ensure full compliance with any prescribed antimicrobial course, completing the entire duration.",
            "Maintain high fluid intake (hydration) to help thin pulmonary secretions and ease clearance.",
            "Avoid exposure to secondary smoke, aerosols, and cold dry air, which irritate bronchial passages.",
            "Adopt incentive spirometry or deep breathing exercises once stable to prevent atelectasis."
        ],
        "disclaimer": (
            "This report is generated by an artificial intelligence platform for educational and clinical support "
            "purposes only. It does not constitute a primary diagnostic decision. All recommendations and predictions "
            "must be verified by a licensed medical practitioner prior to starting any treatment."
        )
    },
    "NORMAL": {
        "clinical_explanation": (
            "The deep learning classification indicates standard pulmonary anatomy. The lung fields appear fully "
            "expanded and clear. There are no signs of patchy consolidation, airspace opacities, focal consolidations, "
            "or major pleural effusions. The cardiomediastinal silhouette and pleural spaces are within normal limits."
        ),
        "possible_causes": [
            "Healthy pulmonary physiology and clear airway pathways.",
            "Symptoms (if presenting) may be related to non-pulmonary causes, such as musculoskeletal strain or gastroesophageal reflux."
        ],
        "recommendations": [
            "No immediate radiographical follow-ups are necessary for pneumonia.",
            "If the patient presents with persistent symptoms (e.g., dyspnea, chronic cough), consider secondary diagnostics like spirometry, allergy panels, or cardiac screening.",
            "Observe standard annual physical review schedules."
        ],
        "lifestyle_suggestions": [
            "Participate in regular cardiovascular exercise to maintain lung volume and physical conditioning.",
            "Practice hand hygiene and stay updated with respiratory vaccinations (seasonal flu, pneumococcal vaccine).",
            "Maintain a smoke-free environment to optimize respiratory health."
        ],
        "disclaimer": (
            "This report is generated by an artificial intelligence platform for educational and clinical support "
            "purposes only. It does not constitute a primary diagnostic decision. All recommendations and predictions "
            "must be verified by a licensed medical practitioner prior to starting any treatment."
        )
    }
}

async def generate_ai_report(prediction_class: str, confidence: float, patient_name: str = "Anonymous Patient") -> dict:
    """
    Generates a structured medical report using Gemini API or local clinical fallback.
    """
    api_key = os.getenv("GEMINI_API_KEY")
    prediction_class = prediction_class.upper()
    
    # Check fallback availability
    fallback_data = CLINICAL_CATALOG.get(prediction_class, CLINICAL_CATALOG["NORMAL"])
    
    if not api_key:
        print("GEMINI_API_KEY not configured. Generating report using local clinical catalog...")
        return {
            "patient_summary": f"Patient: {patient_name}. Diagnostic analysis shows high similarity to {prediction_class.lower()} characteristics with {confidence*100:.1f}% confidence.",
            **fallback_data
        }
        
    try:
        # Configure Gemini API
        genai.configure(api_key=api_key)
        
        # We can use gemini-2.5-flash or fallback to gemini-1.5-flash
        model = genai.GenerativeModel('gemini-2.5-flash')
        
        prompt = f"""
        You are an expert AI Radiologist and Clinical Assistant.
        A deep learning model has predicted the following findings for a chest radiograph:
        - Patient Name: {patient_name}
        - Finding: {prediction_class}
        - Confidence: {confidence*100:.2f}%
        
        Generate a professional clinical report in valid JSON format.
        Do NOT write any preamble, conversational text, or markdown code blocks (such as ```json).
        Return ONLY a JSON object with the following keys and data types:
        - patient_summary (string summarizing patient finding and confidence)
        - clinical_explanation (string explaining the radiological finding and what it means pathologically)
        - possible_causes (array of strings of differential diagnoses or causes)
        - recommendations (array of strings of clinical tests, next steps, or referrals)
        - lifestyle_suggestions (array of strings of home care, wellness, or environmental tips)
        - disclaimer (standard medical disclaimer text)
        """
        
        response = await asyncio.to_thread(
            model.generate_content,
            prompt
        )
        
        # Clean response text from markdown block quotes
        text_content = response.text.strip()
        if text_content.startswith("```"):
            # Strip off backticks
            lines = text_content.splitlines()
            if lines[0].startswith("```"):
                lines = lines[1:]
            if lines[-1].startswith("```"):
                lines = lines[:-1]
            text_content = "\n".join(lines).strip()
            
        report_data = json.loads(text_content)
        
        # Check all required keys exist
        required_keys = ["patient_summary", "clinical_explanation", "possible_causes", "recommendations", "lifestyle_suggestions", "disclaimer"]
        for key in required_keys:
            if key not in report_data:
                # Fill missing keys from local catalog
                report_data[key] = fallback_data[key] if key in fallback_data else f"No data for {key}"
                
        return report_data
        
    except Exception as e:
        print(f"Failed to query Gemini API: {e}. Falling back to local clinical catalog...")
        return {
            "patient_summary": f"Patient: {patient_name}. Diagnostic analysis shows high similarity to {prediction_class.lower()} characteristics with {confidence*100:.1f}% confidence.",
            **fallback_data
        }
